import type { Ejercicio } from './types';

export const ejercicios: Ejercicio[] = [
  { nombre: 'Estiramiento de cuello', descripcion: 'Inclina la cabeza suavemente de lado a lado.', duracion: 30, icon: 'User' },
  { nombre: 'Rotación de hombros', descripcion: 'Gira los hombros hacia adelante y luego hacia atrás.', duracion: 30, icon: 'RotateCw' },
  { nombre: 'Estiramiento de brazos', descripcion: 'Extiende un brazo por encima de la cabeza y dóblalo, usando el otro para un estiramiento suave.', duracion: 45, icon: 'MoveUp' },
  { nombre: 'Estiramiento de muñecas', descripcion: 'Extiende un brazo y flexiona la muñeca hacia arriba y abajo.', duracion: 30, icon: 'Hand' },
  { nombre: 'Giro de torso', descripcion: 'Sentado, gira el torso suavemente a cada lado.', duracion: 45, icon: 'RefreshCw' },
  { nombre: 'Levantamiento de rodillas', descripcion: 'De pie, levanta las rodillas alternadamente hacia el pecho.', duracion: 60, icon: 'MoveUp' },
  { nombre: 'Estiramiento de isquiotibiales', descripcion: 'Sentado, extiende una pierna y trata de tocar la punta del pie.', duracion: 45, icon: 'MoveDown' },
  { nombre: 'Círculos de tobillo', descripcion: 'Levanta un pie y haz círculos con el tobillo en ambas direcciones.', duracion: 30, icon: 'Footprints' },
  { nombre: 'Respiración profunda', descripcion: 'Inhala profundamente por la nariz y exhala lentamente por la boca.', duracion: 60, icon: 'Wind' },
  { nombre: 'Mirada lejana', descripcion: 'Enfoca la vista en un objeto lejano por 20 segundos para relajar los ojos.', duracion: 30, icon: 'Eye' },
  { nombre: 'Estiramiento de espalda', descripcion: 'De pie, entrelaza los dedos y estira los brazos hacia el techo.', duracion: 45, icon: 'StretchVertical' },
  { nombre: 'Sentadillas en silla', descripcion: 'Simula sentarte y levantarte de una silla sin usar las manos.', duracion: 60, icon: 'Armchair' },
  { nombre: 'Flexiones en la pared', descripcion: 'Apoya las manos en la pared y haz flexiones de brazos.', duracion: 60, icon: 'RectangleHorizontal' },
  { nombre: 'Estiramiento de pantorrillas', descripcion: 'Apóyate en una pared y da un paso atrás, manteniendo la pierna recta.', duracion: 45, icon: 'ArrowDownUp' },
  { nombre: 'Marcha en el sitio', descripcion: 'Camina en tu lugar levantando bien las rodillas.', duracion: 60, icon: 'StepForward' },
  { nombre: 'Estiramiento de tríceps', descripcion: 'Pasa un brazo por detrás de la cabeza y tira suavemente del codo con la otra mano.', duracion: 30, icon: 'UserCog' },
  { nombre: 'Encogimiento de hombros', descripcion: 'Levanta los hombros hacia las orejas y luego relájalos.', duracion: 30, icon: 'ChevronsUpDown' },
  { nombre: 'Estiramiento de gato-vaca', descripcion: 'A cuatro patas, arquea y redondea la espalda lentamente.', duracion: 60, icon: 'Cat' },
  { nombre: 'Abrazo de oso', descripcion: 'Cruza los brazos sobre el pecho y abrázate fuerte, luego cambia de brazo.', duracion: 30, icon: 'UserCircle' },
  { nombre: 'Estiramiento de dedos', descripcion: 'Abre y cierra las manos con fuerza varias veces.', duracion: 30, icon: 'HandMetal' },
  { nombre: 'Inclinación pélvica', descripcion: 'Sentado o de pie, contrae los abdominales para aplanar la espalda baja.', duracion: 45, icon: 'Users' },
  { nombre: 'Estiramiento lateral', descripcion: 'De pie, levanta un brazo y estírate hacia el lado contrario.', duracion: 45, icon: 'StretchHorizontal' },
  { nombre: 'Rotación de cadera', descripcion: 'De pie, haz círculos con la cadera en ambas direcciones.', duracion: 45, icon: 'CircleDot' },
  { nombre: 'Palmas oculares', descripcion: 'Frota las palmas para calentarlas y colócalas suavemente sobre los ojos cerrados.', duracion: 60, icon: 'Sparkles' },
  { nombre: 'Estiramiento de cuádriceps', descripcion: 'De pie, sujeta un tobillo y llévalo hacia los glúteos.', duracion: 45, icon: 'PersonStanding' },
  { nombre: 'Sonrisa y relajación facial', descripcion: 'Sonríe ampliamente y luego relaja todos los músculos de la cara.', duracion: 30, icon: 'Smile' },
  { nombre: 'Postura del árbol (simplificada)', descripcion: 'De pie, apoya la planta de un pie en el interior del tobillo contrario.', duracion: 60, icon: 'TreePine' },
  { nombre: 'Elevación de talones', descripcion: 'De pie, ponte de puntillas y baja lentamente.', duracion: 45, icon: 'ArrowUp' },
  { nombre: 'Estiramiento del flexor de la cadera', descripcion: 'Arrodíllate y da un paso adelante, inclinándote sobre la pierna delantera.', duracion: 60, icon: 'Accessibility' },
  { nombre: 'Meditación de un minuto', descripcion: 'Cierra los ojos, concéntrate en tu respiración y despeja tu mente.', duracion: 60, icon: 'BrainCircuit' },
];
